spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
        trace: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 756480474200-8ko607h14vf3n0b0hckp85jnstgq576r.apps.googleusercontent.com
#            client-secret: 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
#            scope: openid, profile, email
#            redirect-uri: "{baseUrl}/login/oauth2/code/google"

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace