
jwt:
  secret: jwtSecret
  accessExpirationsMs: 1800000 # 30 min
  refreshExpirationMs: 604800000 # 7 day

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
        trace: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath*:data.sql

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
    root: debug


