### register category
POST http://localhost:8080/api/category/
Content-Type: application/json
Authorization: Bearer 1231231123

{
  "name": "질문",
  "type": "question"
}

### get category
GET http://localhost:8080/api/category/1

### edit category
PUT http://localhost:8080/api/category/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "질문A",
  "type": "questionA"
}

### delete category
DELETE http://localhost:8080/api/category/1
Authorization: Bearer {{auth_token}}

### search category
GET http://localhost:8080/api/category?page=0&size=10&sort=id,desc&type=name&keyword=TEST