### register community
POST http://localhost:8080/api/community
Content-Type: application/json

{
  "title": "영상에 관한 질문입니다.",
  "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non. Quis hendrerit dolor magna eget est lorem ipsum dolor sit. Volutpat odio facilisis mauris sit amet massa. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Mi eget mauris pharetra et. Non tellus orci ac auctor augue. Elit at imperdiet dui accumsan sit. Ornare arcu dui vivamus arcu felis. Egestas integer eget aliquet nibh praesent. In hac habitasse platea dictumst quisque sagittis purus. Pulvinar elementum integer enim neque volutpat ac.",
  "tags": [
    "jpa", "spring", "querydsl", "springboot", "영속성컨텍스트", "orm"
  ],
  "categoryId": 1
}

### get community
GET http://localhost:8080/api/community/1

### edit community
PUT http://localhost:8080/api/community/1
Content-Type: application/json

{
  "title": "수정~",
  "content": "수정 내용...",
  "tags": [
    "jpa", "spring", "h2", "mariadb"
  ],
  "categoryId": 1
}

### delete community
DELETE http://localhost:8080/api/community/1

### search community
GET http://localhost:8080/api/community?page=0&size=10&sort=id,desc&type=name&keyword=TEST