### register comment
POST http://localhost:8080/api/comment
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "content": "TEST comment content",
  "answerId": 1
}

### edit comment
PUT http://localhost:8080/api/comment/2
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "content": "수정 내용...",
  "answerId": 1
}

### delete comment
DELETE http://localhost:8080/api/comment/2
Authorization: Bearer {{auth_token}}

