### register tag
POST http://localhost:8080/api/tag
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "JPA",
  "community_id": 1
}

### get tags by community
GET http://localhost:8080/api/tag/bycommunity/1

### delete tag
DELETE http://localhost:8080/api/tag/1
Authorization: Bearer {{auth_token}}

