### save test
POST http://localhost:8080/api/test
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "TEST TITLE1",
  "content": "TEST CONTENT1",
  "notice": false
}


### search test
GET http://localhost:8080/api/test?page=0&size=10&sort=id,desc&type=title&keyword=18&
Authorization: Bearer {{auth_token}}


### getOne test
GET http://localhost:8080/api/test/1

### edit test
PUT http://localhost:8080/api/test/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "수정~",
  "content": "수정 내용...",
  "notice": true
}

### delete test
DELETE http://localhost:8080/api/test/1
Authorization: Bearer {{auth_token}}
